### ISSUE TITLE
End-game screen doesn't show up when manually solving a sudoku

### ISSUE THREAD

**Issue by Martin-Surlykke** [gh05tdog/Sudoku_Solver#27]
When solving the sudoku. After filling out every cell, the end screen should show up. I have only been able to achieve this by using the solver. If manually solving the sudoku, nothing shows up after placing the final cell

**Comment by gh05tdog** [comment]
I just tried to solve it manually, and that worked fine. Can you try again to make sure its not a bug anymore? @Martin-Surlykke
